### ISSUE TITLE
Hybrid template cutting off last row on certain mobile phones

### ISSUE THREAD

**Issue by miamimabel** [emailmonday/Cerberus#201]
![template-iphone-outlook](https://user-images.githubusercontent.com/44374217/49118762-93d26480-f273-11e8-8263-66091dd1c79f.jpg)
Hello - I am using the Cerberus Hybrid email template and cannot figure out why it is not rendering correctly on a specific phone (looks great everywhere else!)

The email cuts off the last row before the footer; I am attaching a screenshot of the issue.

The email was viewed on an iPhone 7, in the Outlook App, using Verizon.

Thanks in advance!

**Comment by TedGoas** [comment]
@miamimabel This issue has come up before in mobile Outlook but (to my knowledge) has been fixed. I'm having trouble reproducing this with the current Hybrid template (screenshots below).

I noticed you (or your ESP) as inserted some extra unsubscribe code at the bottom of your screenshot, I wonder if that's causing an issue. Can you trying sending yourself a testing using [Puts Mail](http://putsmail.com)?

---

What I see:

![img_3788](https://user-images.githubusercontent.com/1172461/49162282-88754c80-f2f8-11e8-9548-d31de6f3fc5e.PNG)
![img_3789](https://user-images.githubusercontent.com/1172461/49162286-8ca16a00-f2f8-11e8-9560-804e0b73118f.PNG)

**Comment by miamimabel** [comment]
Hello Ted,

Thank you so much for your quick response.

I will test the email as you suggested and get back to you.

With much appreciation!

--

MABEL PEREZ
Manager, State Web Developer & e-Communications

BEST BUDDIES GLOBAL HEADQUARTERS
100 SE 2nd Street, Suite 2200
Miami, Florida, 33131
P 305.374.2233 x364  |  F 305.377.1969
BESTBUDDIES.ORG<http://www.bestbuddies.org/>

**Comment by miamimabel** [comment]
Hi again, Ted!

I sent the test as suggested and it’s still getting cut off at the bottom (see image).

Any thoughts on how to fix?



From: Mabel Perez
Sent: Wednesday, November 28, 2018 11:59 AM
To: 'TedGoas/Cerberus' <reply@reply.github.com>
Subject: RE: [TedGoas/Cerberus] Hybrid template cutting off last row on certain mobile phones (#201)

Hello Ted,

Thank you so much for your quick response.

I will test the email as you suggested and get back to you.

With much appreciation!

Mabel

**Comment by TedGoas** [comment]
@miamimabel I don't see an attachment, can you use the GitHub UI instead of email to post?

**Comment by TedGoas** [comment]
Just want to let you know I'm not ignoring this but I'm having trouble reproducing it.

As mention above, this has come up before [here](https://github.com/TedGoas/Cerberus/issues/108) and [here](https://github.com/TedGoas/Cerberus/issues/184). In fact I thought we fixed it [details starting with this comment](https://github.com/TedGoas/Cerberus/issues/184#issuecomment-428202810). Something to try on your end?

It is safe to say you're using a fresh copy of the email templates from this repo?

**Comment by TedGoas** [comment]
@miamimabel I just tested this again and am still having trouble reproducing this. Everything appears in tact (and not cut off) in mobile Outlook in Litmus and on my iPhone (up to date).

Can you please test using a fresh copy of Cerberus? And if you still see this issue, can you let me know what versions are of your OS and Outlook app?

**Comment by TedGoas** [comment]
@miamimabel Hey since I can't repro or get much info on this, I'm gonna close. If this is still an issue, please ping me and I can re-open!
