### ISSUE TITLE
Hybrid, responsive and fluid emails are not centered in Gmail on iOS

### ISSUE THREAD

**Issue by vladpekh** [emailmonday/Cerberus#89]
![2016-12-19 18 13](https://cloud.githubusercontent.com/assets/1377208/21332728/78e1d9be-c618-11e6-99b3-860c8c6ddef0.PNG)

-----------------------------

![2016-12-19 18 14 1](https://cloud.githubusercontent.com/assets/1377208/21332735/862de98c-c618-11e6-9b79-7b1175697827.PNG)

-----------------------------

![2016-12-19 18 14](https://cloud.githubusercontent.com/assets/1377208/21332742/8ed17e64-c618-11e6-91ee-70ec71854968.PNG)

-----------------------------
-----------------------------
-----------------------------

It looks like we need something [like this](https://github.com/TedGoas/Cerberus/issues/74) only for Gmail. Any ideas/suggestions?

**Comment by TedGoas** [comment]
@volodymyrpekh Thanks, I hadn't seen this before, I'll look into it. Do you see this bug on any other iPhone? Or just the iPhone SE?

**Comment by vladpekh** [comment]
@TedGoas Same on iPhone 5S (Gmail). I will do tests and screenshots for iPhone 6-7+ tomorrow.

**Comment by philesq** [comment]
Also experiencing a similar issue. The template seems to be aligning left in gmail app, testing on iphone 7.

**Comment by TedGoas** [comment]
This issue appears to impact the **Responsive** and **Fluid** templates as well. In browsing random HTML emails in my inbox, some emails go edge to edge, so it's doesn't seem to be an issue in the Gmail app.

**Comment by TedGoas** [comment]
Confirmed with Gmail team this issue **is only on iOS (both Gmail and Inbox app)**. Android is fine.

**Comment by TedGoas** [comment]
From what I hear, this is a known bug that Gmail is working on, though no ETA.

Until then, here is a hack that should get us by:

1. Add `.email-container` class to the wrapping `<table>` or `<div>`.
2. Add a media query for each iPhone size you'd like to support, like so:

        @media only screen and (min-device-width: 375px) and (max-device-width: 413px) { /* iPhone 6 and 6+ */
            .email-container {
                min-width: 375px !important;
            }
        }

This basically forces the layout to the full-width of the device it's targeting. Since it relies on pixels, it's not a friendly or scalable solution, but it seems to work. Assuming Gmail eventually fixes this iOS bug, I look forward to removing it.

Code and comments appear at [line 88 of Hybrid template](https://github.com/TedGoas/Cerberus/blob/master/cerberus-hybrid.html#L88).

**Comment by vladpekh** [comment]
Thanks @TedGoas for such a quick solution! Happy New Year and all the best in 2017!

**Comment by dariobros** [comment]
hi guys, I have just added this fix to the css code but I noticed that we have another issue - the gutter this time appears in the native iOS Mail app. Has anybody experienced it too? 

![img_9276](https://cloud.githubusercontent.com/assets/13783813/26454062/cf53e0ec-415d-11e7-951c-faf604f555fd.PNG)

**Comment by stephangriesel** [comment]
i had this issue earlier this week. thanks!

**Comment by vnloop** [comment]
I still see a small gap on the right hand size of about 10px or so on Gmail only - iPhone 7plus. Yahoo, same device looks good.

**Comment by vnloop** [comment]
![screen_shot_2018-01-10_at_2_28_50_pm](https://user-images.githubusercontent.com/4235969/34791453-0489a750-f613-11e7-981c-72be739a24c8.png)

**Comment by TedGoas** [comment]
@hitimes Jah. as you may be able to tell from this thread, I never did find a solution that fixes _both_ iOS and Android. I haven't thought about it more since and would welcome the help if you're willing and able! Lemme know and I can re-open this.

**Comment by vnloop** [comment]
I'm working on it, I'll post it here if I find a solution in the next few days.

**Comment by dariobros** [comment]
this was fixed with the code added in style element, plus I added the .email-container class to the main tables (divs if need be), and it works fine:


@media only screen and (min-device-width: 320px) and (max-device-width: 374px) {
/* iPhone 5 and 5S */
.email-container {
	min-width: 320px !important;
}
}
    
@media only screen and (min-device-width: 375px) and (max-device-width: 413px) {
/* iPhone 6 and 6+ */
.email-container {
	min-width: 375px !important;
}
}

**Comment by vnloop** [comment]
I still see the problem @dariobros. I will continue to work on it to get it fixed. Thanks for reopening Ted!

**Comment by dariobros** [comment]
hint: what i have done is I stripped my email to basic table/div and started testing the margins, once you crack the main element you can start adding the rest as the chances are that something may stop it from resizing. if you want i can email you my html code and you can compare/test it.

**Comment by vnloop** [comment]
Sure thing, I'd love to see your solution to it.

I'm adding a navigation to my version as well, now gotta work the breaking points on that as well.

I'm no pro coder, just trying to figure it all out for this series of emails I'm doing at my job.

**Comment by dariobros** [comment]
the solution given above worked for me.

1. during testing remove all elements as they may cause conflicts, and start with 1 simple black table element
2. add the class .email-container to all tables (or the main ones) and add the css code above and see what happens.
 or maybe this code below will help you solve the problem: check the code of this email:

code >>>> https://goo.gl/hUwhkR
image of my app >>>> https://imgsafe.org/image/e956f2c115

**Comment by TedGoas** [comment]
@dariobros Your original solution included the block below. The original intent was to patch a few iPhones, but I hoped this wouldn't become a long-term solution to cover all phones by including a media query for each. Is this how you intend it to work?

```
/* What it does: Removes right gutter in Gmail iOS app: #89 /
/ Create one of these media queries for each additional viewport size you'd like to fix /
/ Thanks to Eric Lepetit (@ericlepetitsf) for help troubleshooting */

@media only screen and (min-device-width: 320px) and (max-device-width: 374px) {
/* iPhone 5 and 5S */
.email-container {
min-width: 320px !important;
}
}

/* What it does: Removes right gutter in Gmail iOS app: #89 /
/ Create one of these media queries for each additional viewport size you'd like to fix /
/ Thanks to Eric Lepetit (@ericlepetitsf) for help troubleshooting */

@media only screen and (min-device-width: 375px) and (max-device-width: 413px) {
/* iPhone 6 and 6+ */
.email-container {
min-width: 375px !important;
}
}
</style>
```

**Comment by dariobros** [comment]
I fully agree. this is the solution that temporary solves the problem, until the Inbox app (if ever) gets an update. I know it's not ideal, but with some type of templates it simply solves the problem. Email code, in general is a massive junk of "fixes" when one really wants the final design to look consistent. so here's just another one :)

**Comment by TedGoas** [comment]
@dariobros @hitimes that is depressing but fair. We should fix this for all iPhone sizes, so I'm thinking of grabbing the [portrait iPhone media queries from here](https://css-tricks.com/snippets/css/media-queries-for-standard-devices/) and replicating this 4-5 times. Think that should do it?

**Comment by dariobros** [comment]
sounds like a plan, things keep changing and the css code may need updating too. (I'm not working on emails at the moment) - what is always good is running tests on each device - that will help eliminate any errors. good luck.

**Comment by TedGoas** [comment]
@dariobros cool, just gut-checking the approach. Even with Litmus, I don't have access _every_ iPhone size, so I'll only be able to test three iPhone sizes and just _hope_ the other two get fixed too 🙈

**Comment by TedGoas** [comment]
> Thanks to Eric Lepetit @ericlepetitsf) for help troubleshooting the original bug.

Crediting this here cause it's a little weird to have this attribution in the source code of each template.

**Comment by TedGoas** [comment]
**UPDATE:** So far this solution referenced above hasn't fixed it. Also while testing, I quickly remembered how not [not every version of Gmail supports media queries](https://emails.hteumeuleu.com/trying-to-make-sense-of-gmail-css-support-after-the-2016-update-53c15151063a), so I wonder if a fix that relies on media queries will truly fix this.

I'm currently stripping down one of the templates to see if I can locate a common trouble-maker and make this work without needing media queries. Eg. the 2-col pattern in the fluid template seems to be a trouble-maker.

I will investigate further, but might take longer than expected.

**Comment by TedGoas** [comment]
Hello everyone, long story short looks like a `media-query` based fix _can_ fix this issue. Yea yea you were right all along 😀. This commit fixes everything I could test on my devices and in Litmus.

There _is_ [a new issue I uncovered](https://github.com/TedGoas/Cerberus/issues/151) in the process, but it's largely unrelated to this issue and can/should be fixed separately.

**Comment by trlangdon** [comment]
Are there any fixes for this same problem on Android Yahoo & Gmail apps?

**Comment by TedGoas** [comment]
@trlangdon This issue _should_ be solved... can you reproduce this issue with a fresh copy of the templates?

**Comment by trlangdon** [comment]
@TedGoas Interesting, I had to apply the above fixes in order to get my gmail ios tests to render correct, but the code I used to work from was probably from a year or so ago. Is there a best place to grab a most recent template to work from?

**Comment by TedGoas** [comment]
@trlangdon Whatever is in `master` is the most up to date. https://github.com/TedGoas/Cerberus
